app:
  stage: "local"
  name: "facade_app"
  dev: true

jwt:
  tokenSecret: "UzI1NiIsInR5cC"
  tokenExpiration: 300

gin:
  name: "facade_gin_app"
  addr: "0.0.0.0:7777"
  caseSensitive: false
  timeout: 30000
  bodyLimit: 0
  enablePrintRoutes: true
  Pprof: false

health:
  addr: "0.0.0.0"
  port: 3524
  pprof: false

mysql:
  pluralTable: true
  maxOpenConn: 500
  maxIdleConn: 10
  maxIdleTime: 100
  maxLifeTime: 3600
  callDepth: 3
  master:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "12345678"
    db: "test"
  slave:
    - addr: "127.0.0.1:3306"
      user: "root"
      password: "12345678"
      db: "test"


mongo:
    addr: "127.0.0.1:27017"
    user: ""
    password: ""
    db: "test"

redis:
  addrs:
    - "localhost:6379"
  user: ""
  password: ""
  db: 0
  isCluster: false


trace:
  ServerLogOn: true
  jaeger:
    jaegerOn: true
    SamplerFreq: 1.0
    CollectorEndpoint: "127.0.0.1:6831"

log:
  callDepth: 4
  defaultLog: "zap"
  console:
    level: "INFO"
    colorful: true
  zap:
    level: "INFO"
    colorful: false
    output: "std"
  file:
    filename: "./app_file_log.txt"
    append: true
    daily: true
    level: "INFO"
    output: "./log.txt"
